# https://taskfile.dev

version: '3'

vars:
  GREETING: j'apprends le go en clonant la command linux ls
  BUILDDIR: ./build
  PROGNAME: eta

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    preconditions:
      - sh: '[[ -d {{.BUILDDIR }} ]]'
        msg: "{{.BUILDDIR}} not found!!!"

    cmds:
      - go build -o {{.BUILDDIR}}/{{.PROGNAME}} .

  release:
    cmds:
      - go build -ldflags="-s -w" -o {{.BUILDDIR}}/{{.PROGNAME}} .

  run:
    cmds:
      - go run .

  run_debug:
    cmds:
      - DEBUG=true go run .

  edit:
    cmds:
      - vim *go
